version: "3.8"
services:
  cyber_factory_backend:
    build:
      dockerfile: docker/backend/Dockerfile
      context: .
    image: "cyber_factory_backend:latest"
    container_name: cyber_factory_backend
    hostname: cyber_factory_backend
    restart: always
    env_file:
      - "./.env"
    ports:
      - "5000:5000"
    depends_on:
      - cyber_factory_postgres
    networks:
      - cyber_factory
  cyber_factory_postgres:
    image: postgres:12.3-alpine
    container_name: cyber_factory_postgres
    restart: always
    env_file:
      - "./.env"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DATABASE}"
    ports:
      - "5432:5432"
    volumes:
      - "~/${DOCKER_SHARED_VOLUME_PATH}/postgres/${POSTGRES_DATABASE}:/var/lib/postgresql/data"
    networks:
      - cyber_factory
  cyber_factory_frontend:
    build:
      dockerfile: docker/frontend/Dockerfile
      context: .
    image: cyber_factory_frontend:latest
    container_name: cyber_factory_frontend
    hostname: cyber_factory_frontend
    env_file:
      - "./.env"
    ports:
      - "3000:80"
    networks:
      - cyber_factory
networks:
  cyber_factory:
      name: cyber_factory
  